/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FeedbackButton {
    }
}
declare global {
    interface HTMLFeedbackButtonElement extends Components.FeedbackButton, HTMLStencilElement {
    }
    var HTMLFeedbackButtonElement: {
        prototype: HTMLFeedbackButtonElement;
        new (): HTMLFeedbackButtonElement;
    };
    interface HTMLElementTagNameMap {
        "feedback-button": HTMLFeedbackButtonElement;
    }
}
declare namespace LocalJSX {
    interface FeedbackButton {
    }
    interface IntrinsicElements {
        "feedback-button": FeedbackButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "feedback-button": LocalJSX.FeedbackButton & JSXBase.HTMLAttributes<HTMLFeedbackButtonElement>;
        }
    }
}
